"""
Generate prototype maintenance history seed JSON (fictional).
Prototype demonstration data – fictional maintenance records.
Writes backend + frontend copies.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BE_OUT = ROOT / "backend" / "app" / "data" / "maintenance_history.json"
FE_OUT = ROOT / "frontend" / "src" / "data" / "maintenanceHistory.json"

# Aircraft: AC-00x maps to MUH-1 / 00x (existing app IDs)
AIRCRAFT = [
    {
        "aircraft_id": "AC-001",
        "aircraft_type": "MUH-1",
        "aircraft_number": "001",
        "total_flight_hours": 1248.5,
        "display_name": "MUH-1 / 기체번호 001",
    },
    {
        "aircraft_id": "AC-002",
        "aircraft_type": "MUH-1",
        "aircraft_number": "002",
        "total_flight_hours": 1102.0,
        "display_name": "MUH-1 / 기체번호 002",
    },
    {
        "aircraft_id": "AC-003",
        "aircraft_type": "MUH-1",
        "aircraft_number": "003",
        "total_flight_hours": 875.4,
        "display_name": "MUH-1 / 기체번호 003",
    },
    {
        "aircraft_id": "AC-004",
        "aircraft_type": "MUH-1",
        "aircraft_number": "004",
        "total_flight_hours": 642.8,
        "display_name": "MUH-1 / 기체번호 004",
    },
    {
        "aircraft_id": "DEMO-KUH-01",
        "aircraft_type": "MUH-1",
        "aircraft_number": "001",
        "total_flight_hours": 1248.5,
        "display_name": "MUH-1 / 기체번호 001 (레거시 ID)",
        "alias_of": "AC-001",
    },
]


def rec(
    mid: str,
    aid: str,
    date: str,
    hours: float,
    *,
    fault_code: str,
    system_category: str,
    component: str,
    symptom: str,
    detected_value: str,
    normal_range: str,
    severity: str,
    diagnosis: str,
    root_cause: str,
    maintenance_action: str,
    replaced_part: str | None,
    technician_note: str | None,
    maintenance_result: str,
    recurrence: bool,
    reference_manual: str,
    symptom_code: str,
    system_code: str,
) -> dict:
    return {
        "maintenance_id": mid,
        "aircraft_id": aid,
        "maintenance_date": date,
        "flight_hours": hours,
        "fault_code": fault_code,
        "system_category": system_category,
        "component": component,
        "symptom": symptom,
        "detected_value": detected_value,
        "normal_range": normal_range,
        "severity": severity,
        "diagnosis": diagnosis,
        "root_cause": root_cause,
        "maintenance_action": maintenance_action,
        "replaced_part": replaced_part,
        "technician_note": technician_note,
        "maintenance_result": maintenance_result,
        "recurrence": recurrence,
        "reference_manual": reference_manual,
        "symptom_code": symptom_code,
        "system_code": system_code,
        "created_at": f"{date}T09:00:00+09:00",
        "is_dummy": True,
    }


def build_records() -> list[dict]:
    rows: list[dict] = []

    # ----- Engine Oil Pressure: 16 cases -----
    # Causes: filter×5, low oil×3, sensor×3, leak×2, pump×2, other×1
    oil = [
        # AC-001 (8)
        ("MNT-ENG-001", "AC-001", "2026-06-15", 1201.4, "32 PSI", "Engine Oil Filter",
         "엔진오일 압력이 32 PSI까지 저하됨", "오일필터 막힘 가능성",
         "오일필터 내부 오염 및 이물질 축적", "엔진오일 필터 점검 및 교체",
         "Engine Oil Filter", "필터 내부에 오염물질 확인",
         "필터 교체 후 엔진오일 압력 53 PSI로 정상 회복", False, "TM-ENG-03 / 4-21"),
        ("MNT-ENG-002", "AC-001", "2026-05-02", 1188.0, "31 PSI", "Engine Oil System",
         "엔진오일 압력 저하 (31 PSI)", "오일량 부족 의",
         "엔진오일 부족", "오일 보충 및 누유점검",
         None, "우측 라인 미세 누유 흔적",
         "오일 보충 후 압력 52 PSI 회복", False, "TM-ENG-03 / 4-18"),
        ("MNT-ENG-003", "AC-001", "2025-11-02", 1056.2, "35 PSI", "Oil Pressure Sensor",
         "엔진오일 압력 지시 저하", "압력센서 이상 의심",
         "압력센서 이상", "오일 압력센서 교체",
         "Oil Pressure Sensor", "센서 출력 드리프트 확인",
         "센서 교체 후 지시값 정상", False, "TM-ENG-03 / 4-30"),
        ("MNT-ENG-004", "AC-001", "2025-07-18", 978.5, "30 PSI", "Engine Oil Line",
         "엔진오일 압력 저하 및 변동", "오일라인 미세 누유 가능성",
         "오일라인 미세 누유", "오일라인 피팅 조임 및 시일 교체",
         "Oil Line Fitting Seal", "배관 연결부 오일 흔적",
         "누유 조치 후 압력 안정", False, "TM-ENG-03 / 4-22"),
        ("MNT-ENG-005", "AC-001", "2025-03-09", 890.1, "28 PSI", "Engine Oil Pump",
         "엔진오일 압력 급격 저하", "오일펌프 성능 저하 의심",
         "오일펌프 성능 저하", "오일펌프 점검 후 교체",
         "Engine Oil Pump", "펌프 내부 마모 흔적",
         "펌프 교체 후 압력 55 PSI 회복", True, "TM-ENG-03 / 4-25"),
        ("MNT-ENG-006", "AC-001", "2024-12-11", 812.4, "33 PSI", "Engine Oil Filter",
         "엔진오일 압력 경고등 점등", "오일필터 오염 가능성",
         "오일필터 오염", "오일필터 교체",
         "Engine Oil Filter", "차압 상승 확인",
         "교체 후 경고 소거, 압력 정상", False, "TM-ENG-03 / 4-21"),
        ("MNT-ENG-007", "AC-001", "2024-08-22", 720.8, "37 PSI", "Sensor Connector",
         "엔진오일 압력 지시 불안정", "센서 커넥터 접촉불량 의심",
         "센서 커넥터 접촉불량", "커넥터 청소 및 재체결",
         None, "핀 산화·헐거움 확인",
         "접촉 복구 후 지시 안정", False, "TM-ENG-03 / 4-31"),
        ("MNT-ENG-008", "AC-001", "2024-04-05", 640.2, "29 PSI", "Engine Oil System",
         "엔진오일 압력 저하", "정비 후 오일량 보충 미흡",
         "정비 후 오일량 보충 미흡", "오일량 재확인 및 보충",
         None, "직전 정비 후 오일량 부족",
         "보충 후 압력 50 PSI 회복", False, "TM-ENG-03 / 4-18"),
        # AC-002 (3)
        ("MNT-ENG-009", "AC-002", "2026-03-14", 1045.6, "31 PSI", "Engine Oil Filter",
         "엔진오일 압력이 31 PSI까지 저하됨", "오일필터 막힘 가능성",
         "오일필터 내부 오염 및 이물질 축적", "엔진오일 필터 교체",
         "Engine Oil Filter", "필터 막힘 확인",
         "교체 후 54 PSI 정상", False, "TM-ENG-03 / 4-21"),
        ("MNT-ENG-010", "AC-002", "2025-09-28", 952.0, "34 PSI", "Engine Oil System",
         "엔진오일 압력 저하", "오일 점도 이상 의심",
         "오일 점도 이상(오염·열화)", "오일 교환 및 필터 동시 교체",
         "Engine Oil / Filter", "오일 색상 암화",
         "오일 교환 후 압력 정상화", False, "TM-ENG-03 / 4-19"),
        ("MNT-ENG-011", "AC-002", "2025-01-17", 801.3, "36 PSI", "Oil Pressure Sensor",
         "엔진오일 압력 지시 이상", "압력센서 이상",
         "압력센서 이상", "압력센서 교체",
         "Oil Pressure Sensor", "교정값 이탈",
         "센서 교체 후 정상 지시", False, "TM-ENG-03 / 4-30"),
        # AC-003 (3)
        ("MNT-ENG-012", "AC-003", "2026-02-08", 820.5, "30 PSI", "Engine Oil Filter",
         "엔진오일 압력 저하", "오일필터 오염",
         "오일필터 오염", "오일필터 교체",
         "Engine Oil Filter", None,
         "압력 51 PSI 회복", False, "TM-ENG-03 / 4-21"),
        ("MNT-ENG-013", "AC-003", "2025-06-19", 710.2, "28 PSI", "Engine Oil Line",
         "엔진오일 압력 저하", "압력배관 막힘 의심",
         "압력배관 막힘", "오일 압력배관 청소 및 점검",
         None, "배관 내 이물질",
         "배관 조치 후 압력 정상", False, "TM-ENG-03 / 4-23"),
        ("MNT-ENG-014", "AC-003", "2024-10-03", 590.7, "32 PSI", "Engine Oil System",
         "엔진오일 압력 저하", "오일량 부족",
         "엔진오일 부족", "오일 보충",
         None, "주유구 주변 누유 없음",
         "보충 후 정상 압력", False, "TM-ENG-03 / 4-18"),
        # AC-004 (2)
        ("MNT-ENG-015", "AC-004", "2025-12-20", 580.1, "33 PSI", "Engine Oil Filter",
         "엔진오일 압력 경고", "오일필터 막힘",
         "오일필터 오염 및 막힘", "오일필터 교체",
         "Engine Oil Filter", "이물질 다량",
         "교체 후 경고 소거", False, "TM-ENG-03 / 4-21"),
        ("MNT-ENG-016", "AC-004", "2025-04-11", 490.6, "35 PSI", "Engine Oil Pump",
         "엔진오일 압력 저하", "오일펌프 이상",
         "오일펌프 성능 저하", "오일펌프 교체",
         "Engine Oil Pump", "토출압 부족",
         "펌프 교체 후 정상", True, "TM-ENG-03 / 4-25"),
    ]
    for mid, aid, date, hrs, val, comp, sym, diag, cause, act, part, note, result, recu, man in oil:
        rows.append(
            rec(
                mid, aid, date, hrs,
                fault_code="ENG-OIL-P-01",
                system_category="Engine Oil System",
                component=comp,
                symptom=sym,
                detected_value=val,
                normal_range="45~65 PSI",
                severity="Warning",
                diagnosis=diag,
                root_cause=cause,
                maintenance_action=act,
                replaced_part=part,
                technician_note=note,
                maintenance_result=result,
                recurrence=recu,
                reference_manual=man,
                symptom_code="ENG_OIL_PRESS_LOW",
                system_code="ENGINE_OIL",
            )
        )

    # ----- Hydraulic: 14 cases -----
    hyd = [
        ("MNT-HYD-001", "AC-001", "2026-05-21", 1195.2, "1780 PSI", "Hydraulic Pump",
         "유압 압력이 정상 범위 이하로 저하됨", "유압펌프 성능 저하 의심",
         "Hydraulic Pump 내부 마모", "유압펌프 점검 후 교체",
         "Hydraulic Pump", "펌프 소음 증가",
         "교체 후 정상 유압 회복 (3050 PSI)", False, "TM-HYD-02 / 3-12"),
        ("MNT-HYD-002", "AC-001", "2025-10-08", 1020.4, "1850 PSI", "Hydraulic Reservoir",
         "유압 압력 저하", "유압유 부족 의심",
         "Hydraulic Fluid 부족", "유압유 보충 및 누유 점검",
         None, "리저버 레벨 LOW",
         "보충 후 압력 정상", False, "TM-HYD-02 / 3-08"),
        ("MNT-HYD-003", "AC-001", "2025-02-14", 860.0, "1720 PSI", "Hydraulic Line",
         "유압 압력 저하 및 누유 흔적", "배관 누유",
         "유압 배관 누유", "배관 피팅 교체 및 누유 조치",
         "Hydraulic Fitting", "우측 라인 누유",
         "누유 제거 후 압력 안정", False, "TM-HYD-02 / 3-15"),
        ("MNT-HYD-004", "AC-001", "2024-09-30", 745.5, "1900 PSI", "Hydraulic Filter",
         "유압 압력 저하", "필터 막힘 의심",
         "유압필터 막힘", "유압필터 교체",
         "Hydraulic Filter", "필터 오염",
         "교체 후 압력 정상화", False, "TM-HYD-02 / 3-10"),
        ("MNT-HYD-005", "AC-001", "2024-06-12", 680.3, "1680 PSI", "Pressure Sensor",
         "유압 압력 지시 이상", "압력센서 이상",
         "유압 압력센서 이상", "압력센서 교체",
         "Hydraulic Pressure Sensor", "지시값 드리프트",
         "센서 교체 후 정상 지시", False, "TM-HYD-02 / 3-20"),
        ("MNT-HYD-006", "AC-002", "2026-04-02", 1060.8, "1750 PSI", "Hydraulic Pump",
         "유압 압력 저하", "Hydraulic Pump 성능 저하",
         "Hydraulic Pump 성능 저하", "유압펌프 교체",
         "Hydraulic Pump", None,
         "교체 후 3100 PSI 회복", False, "TM-HYD-02 / 3-12"),
        ("MNT-HYD-007", "AC-002", "2025-08-16", 920.1, "1820 PSI", "Servo Valve",
         "유압 압력 불안정", "밸브 이상",
         "서보밸브 이상", "서보밸브 점검 후 교체",
         "Servo Valve", "밸브 응답 지연",
         "밸브 교체 후 압력 안정", False, "TM-HYD-02 / 3-18"),
        ("MNT-HYD-008", "AC-002", "2025-03-25", 840.7, "1690 PSI", "Seal",
         "유압 압력 저하", "Seal 손상",
         "Seal 손상으로 인한 내부 누설", "씰 키트 교체",
         "Hydraulic Seal Kit", "내부 누설 확인",
         "씰 교체 후 정상", True, "TM-HYD-02 / 3-16"),
        ("MNT-HYD-009", "AC-002", "2024-11-05", 760.2, "1880 PSI", "Connector",
         "유압 압력 경고 간헐 발생", "커넥터 접촉불량",
         "센서 커넥터 접촉불량", "커넥터 재체결 및 점검",
         None, "핀 헐거움",
         "접촉 복구 후 경고 소거", False, "TM-HYD-02 / 3-21"),
        ("MNT-HYD-010", "AC-003", "2026-01-19", 800.4, "1760 PSI", "Hydraulic Reservoir",
         "유압 압력 저하", "유압유 부족",
         "Hydraulic Fluid 부족", "유압유 보충",
         None, None,
         "보충 후 정상", False, "TM-HYD-02 / 3-08"),
        ("MNT-HYD-011", "AC-003", "2025-07-07", 690.9, "1710 PSI", "Hydraulic Line",
         "유압 압력 저하", "배관 누유",
         "유압 배관 누유", "누유부 배관 교체",
         "Hydraulic Hose", "호스 균열",
         "호스 교체 후 압력 정상", False, "TM-HYD-02 / 3-15"),
        ("MNT-HYD-012", "AC-003", "2024-12-28", 610.5, "1840 PSI", "Hydraulic Filter",
         "유압 압력 저하", "필터 막힘",
         "유압필터 막힘", "유압필터 교체",
         "Hydraulic Filter", None,
         "교체 후 정상 유압", False, "TM-HYD-02 / 3-10"),
        ("MNT-HYD-013", "AC-004", "2025-11-11", 560.0, "1790 PSI", "Hydraulic Pump",
         "유압 압력이 정상보다 낮음", "펌프 성능 저하",
         "Hydraulic Pump 내부 마모", "유압펌프 교체",
         "Hydraulic Pump", None,
         "교체 후 정상 회복", False, "TM-HYD-02 / 3-12"),
        ("MNT-HYD-014", "AC-004", "2025-05-30", 500.2, "1860 PSI", "Pressure Sensor",
         "유압 압력 지시 저하", "압력센서 이상",
         "유압 압력센서 이상", "압력센서 교체",
         "Hydraulic Pressure Sensor", None,
         "센서 교체 후 정상", False, "TM-HYD-02 / 3-20"),
    ]
    for mid, aid, date, hrs, val, comp, sym, diag, cause, act, part, note, result, recu, man in hyd:
        rows.append(
            rec(
                mid, aid, date, hrs,
                fault_code="HYD-P-01",
                system_category="Hydraulic System",
                component=comp,
                symptom=sym,
                detected_value=val,
                normal_range="2500~3500 PSI",
                severity="Warning",
                diagnosis=diag,
                root_cause=cause,
                maintenance_action=act,
                replaced_part=part,
                technician_note=note,
                maintenance_result=result,
                recurrence=recu,
                reference_manual=man,
                symptom_code="HYD_PRESS_LOW",
                system_code="HYDRAULIC",
            )
        )

    # ----- Generator / Electrical: 14 cases (symptom_code GEN_OFF for app match) -----
    gen = [
        ("MNT-GEN-001", "AC-001", "2026-04-18", 1175.0, "22.4 V", "Generator",
         "발전기 출력 전압이 정상 범위 이하로 감소", "Generator 또는 Voltage Regulator 이상 의심",
         "Voltage Regulator 성능 저하", "Voltage Regulator 점검 후 교체",
         "Voltage Regulator", "출력 전압 불안정",
         "교체 후 발전기 출력 정상화 (28.2 V)", False, "TM-ELEC-01 / 5-08"),
        ("MNT-GEN-002", "AC-001", "2025-09-12", 1005.6, "21.8 V", "Generator",
         "발전기 출력 이상", "발전기 출력저하",
         "Generator 내부 마모", "발전기 점검 후 교체",
         "Generator", "브러시 마모",
         "발전기 교체 후 출력 정상", False, "TM-ELEC-01 / 5-04"),
        ("MNT-GEN-003", "AC-001", "2025-01-28", 845.2, "23.1 V", "Wiring Harness",
         "발전기 경고등 점등", "배선 접촉불량",
         "배선 접촉불량", "배선 하네스 점검 및 재체결",
         None, "커넥터 핀 산화",
         "접촉 복구 후 경고 소거", False, "TM-ELEC-01 / 5-12"),
        ("MNT-GEN-004", "AC-001", "2024-07-19", 700.8, "22.0 V", "Circuit Breaker",
         "발전기 출력 이상", "회로차단기 이상",
         "회로차단기 이상", "회로차단기 교체",
         "Generator Circuit Breaker", "차단기 간헐 개방",
         "차단기 교체 후 정상", True, "TM-ELEC-01 / 5-15"),
        ("MNT-GEN-005", "AC-002", "2026-03-01", 1035.4, "22.6 V", "Voltage Regulator",
         "발전기 출력 전압 저하", "Voltage Regulator 이상",
         "Voltage Regulator 이상", "Voltage Regulator 교체",
         "Voltage Regulator", None,
         "교체 후 28.0 V 정상", False, "TM-ELEC-01 / 5-08"),
        ("MNT-GEN-006", "AC-002", "2025-10-22", 980.0, "21.5 V", "Generator Connector",
         "발전기 출력 이상", "Connector 손상",
         "Generator Connector 손상", "커넥터 교체",
         "Generator Connector", "하우징 균열",
         "커넥터 교체 후 정상", False, "TM-ELEC-01 / 5-11"),
        ("MNT-GEN-007", "AC-002", "2025-05-06", 870.3, "23.4 V", "Voltage Sensor",
         "발전기 전압 지시 이상", "전압센서 이상",
         "전압센서 이상", "전압센서 교체",
         "Voltage Sensor", "지시값 오차",
         "센서 교체 후 지시 정상", False, "TM-ELEC-01 / 5-18"),
        ("MNT-GEN-008", "AC-002", "2024-10-15", 740.9, "22.2 V", "Generator",
         "발전기 출력 저하", "발전기 출력저하",
         "Generator 출력 성능 저하", "발전기 오버홀 및 점검",
         None, "부하 증가 시 전압 강하",
         "점검 후 출력 개선", False, "TM-ELEC-01 / 5-04"),
        ("MNT-GEN-009", "AC-003", "2026-02-25", 830.1, "22.9 V", "Voltage Regulator",
         "발전기 출력 이상이 발생", "Voltage Regulator 이상",
         "Voltage Regulator 성능 저하", "Voltage Regulator 교체",
         "Voltage Regulator", None,
         "교체 후 정상화", False, "TM-ELEC-01 / 5-08"),
        ("MNT-GEN-010", "AC-003", "2025-08-01", 720.6, "21.9 V", "Wiring Harness",
         "발전기 경고", "배선 접촉불량",
         "배선 접촉불량", "배선 재작업",
         None, "접지선 헐거움",
         "조치 후 경고 소거", False, "TM-ELEC-01 / 5-12"),
        ("MNT-GEN-011", "AC-003", "2025-02-10", 640.4, "23.0 V", "Generator",
         "발전기 출력 전압 감소", "Generator 내부 마모",
         "Generator 내부 마모", "발전기 교체",
         "Generator", None,
         "교체 후 출력 정상", False, "TM-ELEC-01 / 5-04"),
        ("MNT-GEN-012", "AC-003", "2024-09-03", 560.8, "22.7 V", "Circuit Breaker",
         "발전기 출력 이상", "회로차단기 이상",
         "회로차단기 이상", "회로차단기 교체",
         "Generator Circuit Breaker", None,
         "교체 후 정상", False, "TM-ELEC-01 / 5-15"),
        ("MNT-GEN-013", "AC-004", "2025-12-05", 570.5, "21.6 V", "Voltage Regulator",
         "발전기 출력 저하", "Voltage Regulator 이상",
         "Voltage Regulator 성능 저하", "Voltage Regulator 교체",
         "Voltage Regulator", None,
         "교체 후 정상", False, "TM-ELEC-01 / 5-08"),
        ("MNT-GEN-014", "AC-004", "2025-06-18", 520.3, "22.5 V", "Generator Connector",
         "발전기 출력 이상", "Connector 손상",
         "Generator Connector 손상", "커넥터 교체 및 점검",
         "Generator Connector", None,
         "조치 후 출력 정상", False, "TM-ELEC-01 / 5-11"),
    ]
    for mid, aid, date, hrs, val, comp, sym, diag, cause, act, part, note, result, recu, man in gen:
        rows.append(
            rec(
                mid, aid, date, hrs,
                fault_code="GEN-OFF-01",
                system_category="Generator / Electrical System",
                component=comp,
                symptom=sym,
                detected_value=val,
                normal_range="27~29 V",
                severity="Warning",
                diagnosis=diag,
                root_cause=cause,
                maintenance_action=act,
                replaced_part=part,
                technician_note=note,
                maintenance_result=result,
                recurrence=recu,
                reference_manual=man,
                symptom_code="GEN_OFF",
                system_code="ELECTRICAL",
            )
        )

    # ----- Other systems: ~20 cases (3~5 each family) -----
    other = [
        # Fuel (4)
        ("MNT-FUEL-001", "AC-001", "2025-12-01", 1120.0, "—", "Fuel Filter",
         "연료압력 이상 / 연료필터 막힘 의심", "연료필터 막힘",
         "연료필터 오염", "연료필터 교체", "Fuel Filter", None,
         "필터 교체 후 연료압력 정상", False, "TM-FUEL-01 / 2-10",
         "FUEL_BOOST_FAULT", "FUEL", "Fuel System", "Caution"),
        ("MNT-FUEL-002", "AC-002", "2025-04-20", 860.5, "—", "Fuel Boost Pump",
         "연료 부스트 펌프 경고", "부스트 펌프 이상",
         "Fuel Boost Pump 성능 저하", "부스트 펌프 교체", "Fuel Boost Pump", None,
         "교체 후 경고 소거", False, "TM-FUEL-01 / 2-14",
         "FUEL_BOOST_FAULT", "FUEL", "Fuel System", "Warning"),
        ("MNT-FUEL-003", "AC-003", "2024-11-22", 600.1, "—", "Fuel Quantity Sensor",
         "연료량 지시 이상", "연료량 센서 이상",
         "연료량 센서 이상", "연료량 센서 점검·교정", None, None,
         "교정 후 지시 정상", False, "TM-FUEL-01 / 2-20",
         "FUEL_QTY_WRONG", "FUEL", "Fuel System", "Caution"),
        ("MNT-FUEL-004", "AC-004", "2026-01-08", 590.0, "—", "Fuel Pump CB",
         "연료펌프 차단기 트립", "회로차단기 트립",
         "연료펌프 CB 간헐 트립", "CB 점검 및 펌프 부하 확인", None, None,
         "조치 후 정상 운용", False, "TM-FUEL-01 / 2-16",
         "FUEL_PUMP_CB", "FUEL", "Fuel System", "Caution"),
        # Rotor (3)
        ("MNT-ROT-001", "AC-001", "2025-06-03", 960.4, "—", "Main Rotor",
         "로터 진동 증가", "로터 밸런스 이상",
         "메인로터 트랙/밸런스 이탈", "로터 트랙 및 밸런스 조정", None, "진동 레벨 상승",
         "조정 후 진동 정상 범위", False, "TM-ROT-01 / 6-02",
         "ROTOR_VIBE_HIGH", "ROTOR", "Rotor", "Caution"),
        ("MNT-ROT-002", "AC-002", "2024-08-14", 710.2, "—", "Rotor Hub",
         "로터 진동 증가", "허브 부품 마모",
         "로터 허브 베어링 마모", "허브 베어링 교체", "Rotor Hub Bearing", None,
         "교체 후 진동 감소", False, "TM-ROT-01 / 6-08",
         "ROTOR_VIBE_HIGH", "ROTOR", "Rotor", "Warning"),
        ("MNT-ROT-003", "AC-003", "2025-11-29", 780.8, "—", "Tail Rotor",
         "테일로터 진동 증가", "테일로터 밸런스 이상",
         "테일로터 밸런스 이탈", "테일로터 밸런스 조정", None, None,
         "조정 후 정상", False, "TM-ROT-01 / 6-15",
         "ROTOR_VIBE_HIGH", "ROTOR", "Rotor", "Caution"),
        # Transmission (4)
        ("MNT-XMSN-001", "AC-001", "2026-03-22", 1160.5, "115 C", "Transmission",
         "Transmission Oil Temperature 증가", "미션 오일 냉각 이상",
         "미션 오일쿨러 오염", "오일쿨러 청소 및 오일 점검", None, None,
         "온도 정상 범위 회복", False, "TM-XMSN-01 / 7-05",
         "XMSN_OIL_HOT", "TRANSMISSION", "Transmission", "Warning"),
        ("MNT-XMSN-002", "AC-002", "2025-07-25", 900.0, "40 PSI", "Transmission",
         "미션 오일 압력 저하", "미션 오일량 부족",
         "Transmission Oil 부족", "오일 보충 및 누유 점검", None, None,
         "압력 정상 회복", False, "TM-XMSN-01 / 7-03",
         "XMSN_OIL_PRESS_LOW", "TRANSMISSION", "Transmission", "Warning"),
        ("MNT-XMSN-003", "AC-003", "2024-05-16", 520.4, "—", "Transmission",
         "칩 디텍터 경고", "금속 입자 검출",
         "미션 내부 마모 입자", "칩 디텍터 점검 및 오일 분석", None, "미세 금속분",
         "모니터링 강화, 경고 소거", True, "TM-XMSN-01 / 7-12",
         "XMSN_CHIP_DET", "TRANSMISSION", "Transmission", "Caution"),
        ("MNT-XMSN-004", "AC-004", "2025-09-09", 540.7, "112 C", "Transmission",
         "미션 오일 온도 상승", "오일쿨러 성능 저하",
         "오일쿨러 막힘", "오일쿨러 세척", None, None,
         "온도 정상화", False, "TM-XMSN-01 / 7-05",
         "XMSN_OIL_HOT", "TRANSMISSION", "Transmission", "Caution"),
        # Sensor (3)
        ("MNT-SENS-001", "AC-002", "2026-01-30", 1010.2, "—", "RPM Sensor",
         "RPM Sensor 이상", "RPM 센서 신호 이상",
         "RPM Sensor 고장", "RPM 센서 교체", "RPM Sensor", None,
         "교체 후 지시 정상", False, "TM-AVIO-01 / 8-04",
         "RPM_SENSOR_FAULT", "SENSOR", "Sensor", "Caution"),
        ("MNT-SENS-002", "AC-003", "2025-03-18", 660.0, "—", "Temperature Sensor",
         "온도센서 이상", "온도센서 드리프트",
         "온도센서 이상", "온도센서 교체", "Temp Sensor", None,
         "교체 후 정상", False, "TM-AVIO-01 / 8-06",
         "TEMP_SENSOR_FAULT", "SENSOR", "Sensor", "Caution"),
        ("MNT-SENS-003", "AC-004", "2024-12-02", 450.5, "—", "Pressure Sensor",
         "압력센서 지시 이상", "센서 교정 이탈",
         "범용 압력센서 이상", "센서 교정 및 교체", "Pressure Sensor", None,
         "교정 후 정상", False, "TM-AVIO-01 / 8-02",
         "PRESS_SENSOR_FAULT", "SENSOR", "Sensor", "Caution"),
        # Electrical (non-gen) (3)
        ("MNT-ELEC-001", "AC-001", "2024-11-08", 780.0, "—", "DC Bus",
         "DC 전원 이상", "DC 버스 전압 불안정",
         "정류기/버스 접촉 이상", "DC 버스 연결부 점검", None, None,
         "조치 후 DC 전원 안정", False, "TM-ELEC-01 / 5-22",
         "DC_POWER_FAULT", "ELECTRICAL", "Electrical System", "Caution"),
        ("MNT-ELEC-002", "AC-003", "2025-10-14", 750.3, "—", "Battery",
         "배터리 전압 저하", "배터리 성능 저하",
         "배터리 용량 저하", "배터리 교체", "Aircraft Battery", None,
         "교체 후 정상", False, "TM-ELEC-01 / 5-30",
         "BATT_LOW", "ELECTRICAL", "Electrical System", "Caution"),
        ("MNT-ELEC-003", "AC-004", "2026-02-14", 610.8, "—", "Inverter",
         "인버터 경고", "인버터 출력 이상",
         "인버터 내부 고장", "인버터 교체", "Inverter", None,
         "교체 후 경고 소거", False, "TM-ELEC-01 / 5-28",
         "INV_FAULT", "ELECTRICAL", "Electrical System", "Warning"),
        # Engine Temperature (3)
        ("MNT-TEMP-001", "AC-001", "2025-08-27", 990.5, "—", "Engine",
         "엔진 오일 온도 이상", "오일쿨러 효율 저하",
         "엔진 오일쿨러 오염", "오일쿨러 청소", None, None,
         "온도 정상 범위 회복", False, "TM-ENG-03 / 4-40",
         "ENG_OIL_TEMP_ABNORMAL", "ENGINE", "Engine Temperature", "Caution"),
        ("MNT-TEMP-002", "AC-002", "2024-06-21", 680.4, "—", "Engine",
         "엔진 온도 상승", "냉각계통 이상",
         "냉각 공기 경로 막힘", "냉각 경로 점검·청소", None, None,
         "조치 후 온도 정상", False, "TM-ENG-03 / 4-42",
         "ENG_TEMP_HIGH", "ENGINE", "Engine Temperature", "Warning"),
        ("MNT-TEMP-003", "AC-004", "2025-01-05", 470.2, "—", "Engine",
         "엔진 칩 디텍터 경고", "엔진 마모 입자",
         "엔진 내부 마모 입자 검출", "칩 디텍터 점검 및 오일 분석", None, None,
         "분석 후 정상 운용 지속", False, "TM-ENG-03 / 4-50",
         "ENG_CHIP_DET", "ENGINE", "Engine Temperature", "Caution"),
    ]
    for (
        mid, aid, date, hrs, val, comp, sym, diag, cause, act, part, note, result, recu, man,
        scode, sysc, scat, sev,
    ) in other:
        rows.append(
            rec(
                mid, aid, date, hrs,
                fault_code=scode.replace("_", "-")[:12],
                system_category=scat,
                component=comp,
                symptom=sym,
                detected_value=val,
                normal_range="—",
                severity=sev,
                diagnosis=diag,
                root_cause=cause,
                maintenance_action=act,
                replaced_part=part,
                technician_note=note,
                maintenance_result=result,
                recurrence=recu,
                reference_manual=man,
                symptom_code=scode,
                system_code=sysc,
            )
        )

    # Sort by date desc for readability
    rows.sort(key=lambda r: r["maintenance_date"], reverse=True)
    return rows


def main() -> None:
    records = build_records()
    payload = {
        "version": "2.0",
        "disclaimer": (
            "Prototype demonstration data – fictional maintenance records. "
            "PROTOTYPE DEMO ONLY. Not real aircraft, military, or DELIIS data."
        ),
        "aircraft": AIRCRAFT,
        "records": records,
    }
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    BE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FE_OUT.parent.mkdir(parents=True, exist_ok=True)
    BE_OUT.write_text(text, encoding="utf-8")
    FE_OUT.write_text(text, encoding="utf-8")

    from collections import Counter

    print("total", len(records))
    print("by aircraft", dict(Counter(r["aircraft_id"] for r in records)))
    print("by symptom_code", dict(Counter(r["symptom_code"] for r in records)))
    print("wrote", BE_OUT)
    print("wrote", FE_OUT)


if __name__ == "__main__":
    main()
